language: minimal
cache:
  directories:
  - "$HOME/.cache/Tectonic"
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda install -y -c conda-forge tectonic==0.1.11
script:
- tectonic --keep-intermediates main.tex
- mv main.pdf sample.pdf
deploy:
  provider: releases
  api_key:
    secure: Pk/6nIsMZtDNYzS11z1IOT3W8M6lbxc6BskPsu1yIJnCRUCLXMTxbR95wp2P0vGGqiJsh7TF7ksHLHVvK0qwucoMxTzATVT1l8StzCgEIhbcqVoI7ISvhnPC9h5SUOBy+EZVQ5B+f+BPCID12a2xQ5G6F40L8wUMmLpEQmw/DNdTvvz4+C20zvvLpmUHHEi/S+MCocogSvviric67gR3ZlonHSsoe0wO9nBfT9ClcnY3SbMnJe0+wEzOHTeu/muMpOWS2ibH7ZW3vcRmlWe9qA3pdr+8qY1dlyP9bOjK7v9ZdcSCoA5EqZtGIIRmnlXQ7/S8qt8yqIPDVbwNibMIbCcHvySXVf+CBxRNGQgJIb4jDigLBzu32qXPFRYvKYxheTeNxVQbgDLoPZ5jJORSQMC3k6YaadX7LB94IDyI24/ahUeXPZwYsmBkDZ45PUMblkbMrwrajgMBinCOk33jtYfBCBSKc3E3JFS/A7nQHBvyFJlgccdqWesq+lvL5BAoUK3/A1Pbpj1nyIn1IpqnZ/MO/HSESVfOKveMVMASi8XULk0KfFnamhfyg3vWmSBcnS/dQcrOQXMr6QenU/xU5FC7fBhU066Prz6XQr/sRTsvd+jv1LwcHOe4cHitclnFDblCD3U9FOQ4X4ChZaMPuyX6xBkcrKkNR+9yDRk+bs0=
  file: sample.pdf
  skip_cleanup: true
  on:
    tags: true
