# Taken from https://malramsay.com/post/compiling_latex_on_travis/

language: minimal

cache:
  directories:
  - "$HOME/.cache/Tectonic"

before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda install -y -c conda-forge tectonic==0.1.8

script:
- tectonic --keep-intermediates sample.tex

deploy:
  provider: releases
  api_key:
    secure: L0Ty9pr7HRGq1by7aMvwcG/lCIuirQNMv0r2lNuFp+hoG1le0j1lhZOcQYjX3LEUsHUEV8S4+Bb0KA8rdcrgBmLGsdClIdsWsB7U29aDQLZnDLgT020lHbqsI/hY1akNn7fbs9FyLUC5lWr72YzXfLDF+7ubam/H+Rel3YPqwW58dyQBVvW5VO7i8vpbPNmRg8cyuZAlKKWnrzK4F13Hz8TQpM/8MSfUmzrg54LRFbkkv4SJpjCPs6bMkhez6MhNgrCtdaU0twjbm4bDTiETR8BKIChrVMuJWT67lzI8a2lCcaBZEM3uCGwb4+uXLvZr1l6N+4lubWCUA2iQfL3t/ItS8/+HswwHiZU0R5KGtNnnB1VJTMp5rk8LKiRjR7jquImCsOqtpqdoRJDANbQt4J4h3Tjrja1FiPxvLSZ5NUYe1SXvVSeeEL5I68Z0ea/7A8VBm84l0FIMqXX82XKhqoBQQuqxqQOR9sx/ACgJmIG4bp3w9whMUCNfDSZSURCnW2GMoFc/H5g5VCShs+aPMYTNHdS9T5zlgpEEX4npiH87oKUlJV1ZYZLh0FzW8yQZzPJsYzrtYFT5N83BngOxJ689zYwyGZa+N/BMqqxMEzAgI9XJWMsVnCcJN73ovtqajZkVgWfE3NxH5I/AMusLYU68FwLLDqwErHQD5gfXiVQ=
  file: sample.pdf
  skip_cleanup: true
  on:
    tags: true
